# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'life0.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_annotation(object):
    def setupUi(self, annotation):
        annotation.setObjectName("annotation")
        annotation.resize(800, 629)
        annotation.setStyleSheet("#MainWindow\n"
"{background-image:url(./icon/background.png);}")
        self.centralwidget = QtWidgets.QWidget(annotation)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgba(255, 255, 255，0);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget1 = QtWidgets.QWidget(self.widget_2)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget2 = QtWidgets.QWidget(self.widget1)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.tbtn_loadroot = QtWidgets.QToolButton(self.widget2)
        self.tbtn_loadroot.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.tbtn_loadroot.setObjectName("tbtn_loadroot")
        self.horizontalLayout_4.addWidget(self.tbtn_loadroot)
        self.verticalLayout_3.addWidget(self.widget2)
        self.lineEdit_loadroot = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_loadroot.setEnabled(False)
        self.lineEdit_loadroot.setAutoFillBackground(False)
        self.lineEdit_loadroot.setClearButtonEnabled(False)
        self.lineEdit_loadroot.setObjectName("lineEdit_loadroot")
        self.verticalLayout_3.addWidget(self.lineEdit_loadroot)
        self.verticalLayout.addWidget(self.widget1)
        self.widget3 = QtWidgets.QWidget(self.widget_2)
        self.widget3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.widget3.setObjectName("widget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget4 = QtWidgets.QWidget(self.widget3)
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.tbtn_saveroot = QtWidgets.QToolButton(self.widget4)
        self.tbtn_saveroot.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.tbtn_saveroot.setObjectName("tbtn_saveroot")
        self.horizontalLayout_3.addWidget(self.tbtn_saveroot)
        self.verticalLayout_4.addWidget(self.widget4)
        self.lineEdit_saveroot = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_saveroot.setEnabled(False)
        self.lineEdit_saveroot.setObjectName("lineEdit_saveroot")
        self.verticalLayout_4.addWidget(self.lineEdit_saveroot)
        self.verticalLayout.addWidget(self.widget3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.widget5 = QtWidgets.QWidget(self.widget_2)
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.widget5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.comboBox_rotate_degree = QtWidgets.QComboBox(self.widget5)
        self.comboBox_rotate_degree.setEnabled(True)
        self.comboBox_rotate_degree.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.comboBox_rotate_degree.setMaxCount(20)
        self.comboBox_rotate_degree.setObjectName("comboBox_rotate_degree")
        self.horizontalLayout_8.addWidget(self.comboBox_rotate_degree)
        self.horizontalLayout_8.setStretch(0, 5)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget5)
        self.widget6 = QtWidgets.QWidget(self.widget_2)
        self.widget6.setObjectName("widget6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget7 = QtWidgets.QWidget(self.widget6)
        self.widget7.setObjectName("widget7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.btn_w = QtWidgets.QPushButton(self.widget7)
        self.btn_w.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_w.setText("")
        self.btn_w.setObjectName("btn_w")
        self.horizontalLayout_7.addWidget(self.btn_w)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.widget7)
        self.widget8 = QtWidgets.QWidget(self.widget6)
        self.widget8.setObjectName("widget8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_a = QtWidgets.QPushButton(self.widget8)
        self.btn_a.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_a.setText("")
        self.btn_a.setObjectName("btn_a")
        self.horizontalLayout_2.addWidget(self.btn_a)
        self.btn_reset = QtWidgets.QPushButton(self.widget8)
        self.btn_reset.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_reset.setText("")
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_2.addWidget(self.btn_reset)
        self.btn_d = QtWidgets.QPushButton(self.widget8)
        self.btn_d.setStyleSheet("\n"
"background-color: rgba(255, 255, 255, 0);")
        self.btn_d.setText("")
        self.btn_d.setObjectName("btn_d")
        self.horizontalLayout_2.addWidget(self.btn_d)
        self.verticalLayout_2.addWidget(self.widget8)
        self.widget9 = QtWidgets.QWidget(self.widget6)
        self.widget9.setObjectName("widget9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.btn_s = QtWidgets.QPushButton(self.widget9)
        self.btn_s.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_s.setText("")
        self.btn_s.setObjectName("btn_s")
        self.horizontalLayout_6.addWidget(self.btn_s)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.widget9)
        self.verticalLayout.addWidget(self.widget6)
        self.btn_back = QtWidgets.QPushButton(self.widget_2)
        self.btn_back.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.btn_nxt = QtWidgets.QPushButton(self.widget_2)
        self.btn_nxt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nxt.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_nxt.setCheckable(True)
        self.btn_nxt.setObjectName("btn_nxt")
        self.verticalLayout.addWidget(self.btn_nxt)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.btn_continue = QtWidgets.QPushButton(self.widget_2)
        self.btn_continue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_continue.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.btn_continue.setText("")
        self.btn_continue.setObjectName("btn_continue")
        self.verticalLayout.addWidget(self.btn_continue)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.widget10 = QtWidgets.QWidget(self.widget_2)
        self.widget10.setObjectName("widget10")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_Sym = QtWidgets.QCheckBox(self.widget10)
        self.checkBox_Sym.setObjectName("checkBox_Sym")
        self.horizontalLayout.addWidget(self.checkBox_Sym)
        self.checkBox_del = QtWidgets.QCheckBox(self.widget10)
        self.checkBox_del.setObjectName("checkBox_del")
        self.horizontalLayout.addWidget(self.checkBox_del)
        self.verticalLayout.addWidget(self.widget10)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(3, 4)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(7, 4)
        self.verticalLayout.setStretch(11, 2)
        self.horizontalLayout_9.addWidget(self.widget_2)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_9.addWidget(self.line)
        self.widget_show = QtWidgets.QWidget(self.widget)
        self.widget_show.setObjectName("widget_show")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_show)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_label = QtWidgets.QLabel(self.widget_show)
        self.label_label.setText("")
        self.label_label.setObjectName("label_label")
        self.verticalLayout_5.addWidget(self.label_label)
        self.label = QtWidgets.QLabel(self.widget_show)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 20)
        self.horizontalLayout_9.addWidget(self.widget_show)
        self.horizontalLayout_9.setStretch(0, 5)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 50)
        self.horizontalLayout_10.addWidget(self.widget)
        annotation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(annotation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        annotation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(annotation)
        self.statusbar.setObjectName("statusbar")
        annotation.setStatusBar(self.statusbar)
        self.actionexit = QtWidgets.QAction(annotation)
        self.actionexit.setObjectName("actionexit")
        self.actionopen = QtWidgets.QAction(annotation)
        self.actionopen.setObjectName("actionopen")
        self.actionpre = QtWidgets.QAction(annotation)
        self.actionpre.setObjectName("actionpre")
        self.actionnext = QtWidgets.QAction(annotation)
        self.actionnext.setObjectName("actionnext")
        self.actionleft = QtWidgets.QAction(annotation)
        self.actionleft.setObjectName("actionleft")
        self.actionright = QtWidgets.QAction(annotation)
        self.actionright.setObjectName("actionright")
        self.actionup = QtWidgets.QAction(annotation)
        self.actionup.setObjectName("actionup")
        self.actiondown = QtWidgets.QAction(annotation)
        self.actiondown.setObjectName("actiondown")

        self.retranslateUi(annotation)
        self.comboBox_rotate_degree.setCurrentIndex(-1)
        self.actionexit.triggered.connect(annotation.close)
        QtCore.QMetaObject.connectSlotsByName(annotation)

    def retranslateUi(self, annotation):
        _translate = QtCore.QCoreApplication.translate
        annotation.setWindowTitle(_translate("annotation", "MainWindow"))
        self.label_3.setText(_translate("annotation", "load"))
        self.tbtn_loadroot.setText(_translate("annotation", "..."))
        self.label_2.setText(_translate("annotation", "save"))
        self.tbtn_saveroot.setText(_translate("annotation", "..."))
        self.label_4.setText(_translate("annotation", "rotate degree"))
        self.btn_back.setText(_translate("annotation", "pre"))
        self.btn_nxt.setText(_translate("annotation", "next"))
        self.checkBox_Sym.setText(_translate("annotation", "symmetric"))
        self.checkBox_del.setText(_translate("annotation", "delete"))
        self.actionexit.setText(_translate("annotation", "exit"))
        self.actionexit.setShortcut(_translate("annotation", "Esc"))
        self.actionopen.setText(_translate("annotation", "open"))
        self.actionpre.setText(_translate("annotation", "pre"))
        self.actionpre.setShortcut(_translate("annotation", "K"))
        self.actionnext.setText(_translate("annotation", "next"))
        self.actionnext.setShortcut(_translate("annotation", "L"))
        self.actionleft.setText(_translate("annotation", "show"))
        self.actionleft.setShortcut(_translate("annotation", "A"))
        self.actionright.setText(_translate("annotation", "right"))
        self.actionright.setShortcut(_translate("annotation", "D"))
        self.actionup.setText(_translate("annotation", "up"))
        self.actionup.setShortcut(_translate("annotation", "W"))
        self.actiondown.setText(_translate("annotation", "down"))
        self.actiondown.setShortcut(_translate("annotation", "S"))
